### PR TITLE
add support for websocket close code; other bug fixes

### LINKED ISSUE #3: Implement Close Code re: RFC
Add support for close codes that are required for some API implementations.

https://tools.ietf.org/html/rfc6455#section-7.1.5

### LINKED ISSUE #4: Can't change `maxFrameSize` in WebSocketUpgrader
How to change `maxFrameSize` to bigger value than default one (16384 bytes)?
Due to private modification can't set my own, is the way to solve this?

### PR DESCRIPTION
**Pull request by tanner0101**
- [x] adds `onCloseCode(...)` method to `WebSocket`.
- [x] adds `close(code:)` overload to `WebSocket` close method.
- [ ] remove debug print
- [x] fixes #3 
- [x] adds `maxFrameSize` param to server protocol upgrader.
- [x] fixes #4 
- [ ] randomly generate seckey

### CODE REVIEW

File: Sources/WebSocket/WebSocketHandler.swift [hunk 1]
```diff
@@ -36,6 +32,7 @@ private final class WebSocketHandler: ChannelInboundHandler {
     /// See `ChannelInboundHandler`.
     func channelRead(ctx: ChannelHandlerContext, data: NIOAny) {
         var frame = self.unwrapInboundIn(data)
+        print("READ: \(frame)")
```
Comment (4np) [inline Sources/WebSocket/WebSocketHandler.swift]: @tanner0101 : you forgot to remove a debug line :)

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 43 coins.
